server:
  port: 8082
  servlet:
    context-path: /hotels/
spring:
  application:
    name: hotels-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.local:8080/auth/realms/spring-cloud-gateway-realm
